version: '3.5'
services:
  web:
    container_name: web_app_react
    command: yarn start
    build: web/
    volumes:
      - ./web/app:/app
    ports: 
        - 3000:3000
  api:
    container_name: node_api
    command: yarn start
    build: api/
    volumes: 
      - ./api/app:/app
    ports: 
      - 8000:8000